---

- name: Creates directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ jenkins_workdir }}"
    - "{{ jenkins_workdir }}/jenkins_home"

- name: Create symbolic link to jenkins_home
  become: true
  file:
    src: "{{ jenkins_workdir }}/jenkins_home"
    dest: "/var/jenkins_home"
    state: link

- name: Upload docker-compose.yml and add-docker-group.sh to host
  copy:
    src: "{{ item }}"
    dest: "{{ jenkins_workdir }}/{{ item }}"
  with_items:
    - docker-compose.yml
    - add-docker-group.sh

- name: Run docker-compose.yml
  docker_service:
    project_src: "{{ jenkins_workdir }}"
  environment:
    DOCKER_COMPOSE_JENKINS_PORT: "{{ jenkins_port }}"
  register: jenkins_container_result
  notify:
    - Create docker group inside a container and add to it jenkins user
    - Restart jenkins container
    - Get initial admin password
