version: '3'

services:

  jenkins:
    image: eriklotin/jenkins
    container_name: jenkins
    privileged: true
    restart: unless-stopped
    ports:
      - ${DOCKER_COMPOSE_JENKINS_PORT}:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker